### ISSUE TITLE
Error with example counter

### ISSUE THREAD

**Issue by gkvoelkl** [lindsaykwardell/elm-vue-bridge#9]
Hello, 

I tried the elm counter example with vue cli.

Got an error in browser:

TypeError: undefined is not an object (evaluating 'comp.props')

What could it be?

Thanks.

Best regards Gerhard

**Comment by lindsaykwardell** [comment]
Hello, I'm looking into this. I may just need to update some dependencies

**Comment by lindsaykwardell** [comment]
You said you were using Vue CLI, is that correct? Which command did you use to initialize your app? I want to make sure I'm looking at the correct template.

**Comment by lindsaykwardell** [comment]
Closing until more information is provided.
